### PR TITLE
Update vcf_to_bq.py

### PR DESCRIPTION
**Pull request by CNuge**
There was a stray r before the """comment """ on line 15 I removed.

### CODE REVIEW

**Comment by CNuge** [comment]
Hello google robot, I signed the form!

**Comment by arostamianfar** [comment]
Thanks for the PR! However, the 'r' is actually there by design as the comment includes a backslash. See: https://docs.python.org/2/reference/lexical_analysis.html#string-literals

**Comment by CNuge** [comment]
Ah I see my mistake... thanks for teaching me that!

**Comment by arostamianfar** [comment]
np! thanks for reviewing our code :) please feel free to make PRs if you encounter any issues/bugs. We're just getting started, but I'll write some docs about how to report and fix bugs/features.

**Pull request closed without merging**
